int gp_cdsp_set_badpixel_ob(int cdsp_handle, int obval);
int gp_cdsp_set_lenscmp(int cdsp_handle);
int gp_cdsp_set_wb_gain(int cdsp_handle);
int gp_cdsp_set_aeawb_window(int cdsp_handle, int width, int height, int tagetY);
int gp_cdsp_set_gamma(int cdsp_handle);
int gp_cdsp_set_colormatrix(int cdsp_handle);
int gp_cdsp_set_edge(int cdsp_handle, int sharpness);
int gp_cdsp_set_new_denoise(int cdsp_handle, int sharpness);
int gp_cdsp_set_suppression(int cdsp_handle);
int gp_cdsp_set_saturation(int cdsp_handle);
int gp_cdsp_set_awb_mode(int cdsp_handle, int mode);
int gp_cdsp_set_ev_val(int cdsp_handle, int ev);
int gp_cdsp_raw_special_mode(int cdsp_handle, int mode);
int gp_cdsp_set_iso(int cdsp_handle, int iso);
void gp_cdsp_set_yuv_scale(int cdsp_handle, int dst_w, int dst_h);
void gp_cdsp_enable(int handle, int width, int height, void *user_preference);
int gp_cdsp_get_awb_mode();
int gp_cdsp_get_edge();
int gp_cdsp_get_ev();
int gp_cdsp_get_raw_special_mode();
int gp_cdsp_get_iso();
void gp_cdsp_get_yuv_scale(int* width, int* height);
