include $(TOPDIR)/out/$(PRODUCT)/config/sysconfig.mak
# ###############################################################
# LCD1 panels
# ###############################################################

obj-m += $(SYSCONFIG_DISP1_PANEL).o