include $(TOPDIR)/out/$(PRODUCT)/config/sysconfig.mak
# ###############################################################
# LCD panels
# ###############################################################

obj-m += $(SYSCONFIG_DISP0_PANEL).o
