enum{
	DV_CMD_MIN=0,
	CMD_START_DV,	//开始录像
	CMD_STOP_DV,	//结束录像
	CMD_DO_CAPTURE,	//拍照
	CMD_SET_DIR,	//设置路径及文件名
	CMD_SET_DV_RESOLUTION,
	CMD_SET_LOOPRECORDING,
	CMD_SET_WDR,
	CMD_SET_EXPOSURE,
	CMD_SET_MD,
	CMD_SET_RECORD_AUDIO,
	CMD_SET_DV_DATE_STAMP,
	CMD_SET_DC_RESOLUTION,
	CMD_SET_SEQUENCE,
	CMD_SET_QUALITY,
	CMD_SET_SHARPNESS,
	CMD_SET_AWB,
	CMD_SET_COLOR,
	CMD_SET_ISO,
	CMD_SET_ANTI_SHAKING,
	CMD_SET_DC_DATE_STAMP,
	CMD_SET_TVMODE,
	CMD_SET_FREQUENCY,
	CMD_SET_DISPLAY_MODE,
	CMD_SET_MD_DV_START,
	CMD_SET_MD_DV_STOP,
	CMD_SET_EXIT,
	CMD_SET_LOOPRECORDING_INT,
	CMD_SET_ZOOM, //28
	CMD_SET_LOCK_FILE,
	CMD_SET_SEQUENCE_INT,
	CMD_READY_KEY,
	CMD_SET_DEFAULT_SETTING,
	CMD_SET_DATE_TYPE,
	CMD_SET_SDC_ERROR,
	CMD_SET_LDW_EN,
	CMD_SET_LDW_LOW_SPEED,
	CMD_SET_LDW_HIGH_SPEED,
	CMD_SET_LDW_INT,	
	CMD_SET_TIME_LAPSE,
	CMD_SET_LDW_LINE,
	CMD_SET_LDW_LINE2DISP,
	CMD_SET_SENSOR_FLIP,
	DV_CMD_MAX
};
void DV_pipe_init(void);
void DC_pipe_init(void);
void CVR_Set_PIPE(UINT32 CMD,int mode);
void CVR_Set_PIPE_With_CMD(UINT32 CMD,UINT8 wait);
void DV_set_dir(char *dir);
int DV_check_exist();
void DV_idle();