include $(TOPDIR)/out/$(PRODUCT)/config/sysconfig.mak
#
# Makefile for the KEYBOARD
#

ifeq ($(SYSCONFIG_KEYBOARD_DEVICE),gpba02a_module)
	obj-m += gpba02a_module.o
	gpba02a_module-objs := gpba02a.o
endif
