include $(TOPDIR)/out/$(PRODUCT)/config/sysconfig.mak
#
# Makefile for the TOUCHPAD
#

ifeq ($(SYSCONFIG_TOUCHPAD_DEVICE),tpd_dok_t6740b_module)
	obj-m += tpd_dok_t6740b_module.o
	tpd_dok_t6740b_module-objs := tpd_dok_t6740b.o
endif