include $(TOPDIR)/out/$(PRODUCT)/config/sysconfig.mak
# ###############################################################
# gsensors
# ###############################################################

obj-m += $(SYSCONFIG_A_SENSOR_DEVICE).o
