include $(TOPDIR)/out/$(PRODUCT)/config/sysconfig.mak
# ###############################################################
# LCM1 panels
# ###############################################################

obj-m += $(SYSCONFIG_DISP1_PANEL).o
